name: Build
on:
  push:

jobs:
  windows:
    runs-on: windows-latest
    steps:
      - uses: hecrj/setup-rust-action@v1
      - uses: actions/checkout@v2
      - name: Enable static CRT linkage
        run: |
          mkdir .cargo
          echo '[target.x86_64-pc-windows-msvc]' >> .cargo/config
          echo 'rustflags = ["-Ctarget-feature=+crt-static"]' >> .cargo/config
      - name: Build binary
        run: cargo build --verbose --release
      - name: Strip binary
        run: strip target/release/cursor-speed-pin.exe
      - name: Archive binary
        uses: actions/upload-artifact@v1
        with:
          name: cursor-speed-pin.exe
          path: target/release/cursor-speed-pin.exe
      - name: Release binary
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v1
        with:
          files: |
            target/release/cursor-speed-pin.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
